/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DocumentReference = IDL.Record({
  'documentType' : IDL.Text,
  'uploadStatus' : IDL.Bool,
  'fileName' : IDL.Text,
});
export const AcademicRecord = IDL.Record({
  'marksheetRef' : IDL.Opt(IDL.Text),
  'institution' : IDL.Text,
  'year' : IDL.Nat,
  'degree' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const DisabilityStatus = IDL.Variant({
  'none' : IDL.Null,
  'hearingImpaired' : IDL.Null,
  'physicalImpaired' : IDL.Null,
  'sightImpaired' : IDL.Null,
});
export const CareerAchievement = IDL.Record({
  'duration' : IDL.Text,
  'role' : IDL.Text,
  'employer' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Category = IDL.Variant({
  'sc' : IDL.Null,
  'st' : IDL.Null,
  'obc' : IDL.Null,
  'general' : IDL.Null,
});
export const Student = IDL.Record({
  'profileCompletionPercentage' : IDL.Nat,
  'instituteName' : IDL.Text,
  'documents' : IDL.Vec(DocumentReference),
  'courseLevel' : IDL.Text,
  'academicRecords' : IDL.Vec(AcademicRecord),
  'owner' : IDL.Principal,
  'disabilityStatus' : DisabilityStatus,
  'createdAt' : IDL.Int,
  'profileId' : IDL.Nat,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'careerAchievements' : IDL.Vec(CareerAchievement),
  'email' : IDL.Text,
  'district' : IDL.Text,
  'updatedAt' : IDL.Int,
  'state' : IDL.Text,
  'currentYear' : IDL.Nat,
  'gender' : Gender,
  'category' : Category,
  'courseName' : IDL.Text,
  'annualFamilyIncome' : IDL.Text,
});
export const DocumentVerificationResult = IDL.Record({
  'status' : IDL.Variant({
    'V2' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  }),
  'updatedTimestamp' : IDL.Int,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cleanDemoStudents' : IDL.Func([], [IDL.Text], []),
  'connectDigiLocker' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadDemoStudents' : IDL.Func([], [], []),
  'registerStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Gender,
        Category,
        DisabilityStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
  'verifyDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [DocumentVerificationResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DocumentReference = IDL.Record({
    'documentType' : IDL.Text,
    'uploadStatus' : IDL.Bool,
    'fileName' : IDL.Text,
  });
  const AcademicRecord = IDL.Record({
    'marksheetRef' : IDL.Opt(IDL.Text),
    'institution' : IDL.Text,
    'year' : IDL.Nat,
    'degree' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const DisabilityStatus = IDL.Variant({
    'none' : IDL.Null,
    'hearingImpaired' : IDL.Null,
    'physicalImpaired' : IDL.Null,
    'sightImpaired' : IDL.Null,
  });
  const CareerAchievement = IDL.Record({
    'duration' : IDL.Text,
    'role' : IDL.Text,
    'employer' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Category = IDL.Variant({
    'sc' : IDL.Null,
    'st' : IDL.Null,
    'obc' : IDL.Null,
    'general' : IDL.Null,
  });
  const Student = IDL.Record({
    'profileCompletionPercentage' : IDL.Nat,
    'instituteName' : IDL.Text,
    'documents' : IDL.Vec(DocumentReference),
    'courseLevel' : IDL.Text,
    'academicRecords' : IDL.Vec(AcademicRecord),
    'owner' : IDL.Principal,
    'disabilityStatus' : DisabilityStatus,
    'createdAt' : IDL.Int,
    'profileId' : IDL.Nat,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'careerAchievements' : IDL.Vec(CareerAchievement),
    'email' : IDL.Text,
    'district' : IDL.Text,
    'updatedAt' : IDL.Int,
    'state' : IDL.Text,
    'currentYear' : IDL.Nat,
    'gender' : Gender,
    'category' : Category,
    'courseName' : IDL.Text,
    'annualFamilyIncome' : IDL.Text,
  });
  const DocumentVerificationResult = IDL.Record({
    'status' : IDL.Variant({
      'V2' : IDL.Null,
      'Approved' : IDL.Null,
      'Rejected' : IDL.Null,
      'Pending' : IDL.Null,
    }),
    'updatedTimestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cleanDemoStudents' : IDL.Func([], [IDL.Text], []),
    'connectDigiLocker' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadDemoStudents' : IDL.Func([], [], []),
    'registerStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Gender,
          Category,
          DisabilityStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
    'verifyDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [DocumentVerificationResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };