/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicRecord {
  'marksheetRef' : [] | [string],
  'institution' : string,
  'year' : bigint,
  'degree' : string,
  'percentage' : number,
}
export interface CareerAchievement {
  'duration' : string,
  'role' : string,
  'employer' : string,
  'skills' : Array<string>,
}
export type Category = { 'sc' : null } |
  { 'st' : null } |
  { 'obc' : null } |
  { 'general' : null };
export type DisabilityStatus = { 'none' : null } |
  { 'hearingImpaired' : null } |
  { 'physicalImpaired' : null } |
  { 'sightImpaired' : null };
export interface DocumentReference {
  'documentType' : string,
  'uploadStatus' : boolean,
  'fileName' : string,
}
export interface DocumentVerificationResult {
  'status' : { 'V2' : null } |
    { 'Approved' : null } |
    { 'Rejected' : null } |
    { 'Pending' : null },
  'updatedTimestamp' : bigint,
  'reason' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Student {
  'profileCompletionPercentage' : bigint,
  'instituteName' : string,
  'documents' : Array<DocumentReference>,
  'courseLevel' : string,
  'academicRecords' : Array<AcademicRecord>,
  'owner' : Principal,
  'disabilityStatus' : DisabilityStatus,
  'createdAt' : bigint,
  'profileId' : bigint,
  'fullName' : string,
  'mobileNumber' : string,
  'careerAchievements' : Array<CareerAchievement>,
  'email' : string,
  'district' : string,
  'updatedAt' : bigint,
  'state' : string,
  'currentYear' : bigint,
  'gender' : Gender,
  'category' : Category,
  'courseName' : string,
  'annualFamilyIncome' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cleanDemoStudents' : ActorMethod<[], string>,
  'connectDigiLocker' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[], [] | [Student]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Load demo students (admin-only).
   */
  'loadDemoStudents' : ActorMethod<[], undefined>,
  'registerStudent' : ActorMethod<
    [
      string,
      string,
      string,
      Gender,
      Category,
      DisabilityStatus,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadDocument' : ActorMethod<[bigint, string, string], string>,
  'verifyDocument' : ActorMethod<
    [bigint, string, string],
    DocumentVerificationResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];