/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DocumentReference {
    documentType: string;
    uploadStatus: boolean;
    fileName: string;
}
export interface MasterUserRecord {
    dob: string;
    documents: Array<DocumentReference>;
    academics: Array<AcademicRecord>;
    name: string;
    email: string;
    gender: Gender;
    category: Category;
    career: Array<CareerAchievement>;
}
export interface Scholarship {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    description: string;
    deadline: string;
    eligibility: {
        category: Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
}
export interface CareerAchievement {
    duration: string;
    role: string;
    employer: string;
    skills: Array<string>;
}
export interface EligibilityCheckResult {
    missingDocuments: Array<string>;
    isEligible: boolean;
    unmetRequirements: Array<string>;
}
export interface AcademicRecord {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}
export interface ProfileCompletionResult {
    completionPercentage: number;
    missingFields: Array<string>;
}
export interface ScholarshipApplication {
    status: ApplicationStatus;
    userId: Principal;
    filledFields: MasterUserRecord;
    scholarshipId: bigint;
}
export enum ApplicationStatus {
    submitted = "submitted",
    underReview = "underReview",
    approved = "approved",
    rejected = "rejected",
    draft = "draft"
}
export enum Category {
    sc = "sc",
    st = "st",
    obc = "obc",
    general = "general"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Apply to a scholarship. Requires #user role.
     */
    applyToScholarship(scholarshipId: bigint, application: ScholarshipApplication): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Return a pre-populated application form from the user's Master User Record.
     * / Caller must be the owner of the record or an admin, because this exposes
     * / private personal, academic, and career data.
     */
    autoFillApplication(scholarshipId: bigint, user: Principal): Promise<MasterUserRecord | null>;
    /**
     * / Check eligibility of a user for a scholarship.
     * / Caller must be the owner of the record or an admin, because the result
     * / exposes private academic and career data.
     */
    checkEligibility(scholarshipId: bigint, user: Principal): Promise<EligibilityCheckResult>;
    /**
     * / Create a new scholarship. Admin only.
     */
    createScholarship(scholarship: Scholarship): Promise<bigint>;
    /**
     * / Get the calling user's own Master User Record.
     */
    getCallerUserProfile(): Promise<MasterUserRecord | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Calculate the profile completion score for a user.
     * / Caller must be the owner of the record or an admin, because the result
     * / reveals which private fields are missing.
     */
    getProfileCompletion(user: Principal): Promise<ProfileCompletionResult>;
    /**
     * / Get a single scholarship by id. Public — no auth required.
     */
    getScholarship(id: bigint): Promise<Scholarship>;
    /**
     * / Retrieve all applications for a user. Caller must be the owner or an admin.
     */
    getUserApplications(user: Principal): Promise<Array<ScholarshipApplication>>;
    /**
     * / Fetch another user's profile. Caller must be the owner or an admin.
     */
    getUserProfile(user: Principal): Promise<MasterUserRecord | null>;
    /**
     * / Retrieve a user record. Caller must be the owner or an admin.
     */
    getUserRecord(user: Principal): Promise<MasterUserRecord | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List all scholarships. Public — no auth required.
     */
    listScholarships(): Promise<Array<Scholarship>>;
    /**
     * / Save/update the calling user's own Master User Record.
     */
    saveCallerUserProfile(record: MasterUserRecord): Promise<void>;
    /**
     * / Update the calling user's own Master User Record.
     */
    updateUserRecord(record: MasterUserRecord): Promise<void>;
}
import type { AcademicRecord as _AcademicRecord, ApplicationStatus as _ApplicationStatus, CareerAchievement as _CareerAchievement, Category as _Category, DocumentReference as _DocumentReference, Gender as _Gender, MasterUserRecord as _MasterUserRecord, Scholarship as _Scholarship, ScholarshipApplication as _ScholarshipApplication, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async applyToScholarship(arg0: bigint, arg1: ScholarshipApplication): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToScholarship(arg0, to_candid_ScholarshipApplication_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToScholarship(arg0, to_candid_ScholarshipApplication_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autoFillApplication(arg0: bigint, arg1: Principal): Promise<MasterUserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.autoFillApplication(arg0, arg1);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoFillApplication(arg0, arg1);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkEligibility(arg0: bigint, arg1: Principal): Promise<EligibilityCheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkEligibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkEligibility(arg0, arg1);
            return result;
        }
    }
    async createScholarship(arg0: Scholarship): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createScholarship(to_candid_Scholarship_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScholarship(to_candid_Scholarship_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<MasterUserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileCompletion(arg0: Principal): Promise<ProfileCompletionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileCompletion(arg0);
            return result;
        }
    }
    async getScholarship(arg0: bigint): Promise<Scholarship> {
        if (this.processError) {
            try {
                const result = await this.actor.getScholarship(arg0);
                return from_candid_Scholarship_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScholarship(arg0);
            return from_candid_Scholarship_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserApplications(arg0: Principal): Promise<Array<ScholarshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserApplications(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserApplications(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<MasterUserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRecord(arg0: Principal): Promise<MasterUserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRecord(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRecord(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listScholarships(): Promise<Array<Scholarship>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScholarships();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScholarships();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: MasterUserRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_MasterUserRecord_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_MasterUserRecord_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserRecord(arg0: MasterUserRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRecord(to_candid_MasterUserRecord_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRecord(to_candid_MasterUserRecord_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AcademicRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicRecord): AcademicRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_MasterUserRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MasterUserRecord): MasterUserRecord {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ScholarshipApplication_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScholarshipApplication): ScholarshipApplication {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Scholarship_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scholarship): Scholarship {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MasterUserRecord]): MasterUserRecord | null {
    return value.length === 0 ? null : from_candid_MasterUserRecord_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: string;
    documents: Array<_DocumentReference>;
    academics: Array<_AcademicRecord>;
    name: string;
    email: string;
    gender: _Gender;
    category: _Category;
    career: Array<_CareerAchievement>;
}): {
    dob: string;
    documents: Array<DocumentReference>;
    academics: Array<AcademicRecord>;
    name: string;
    email: string;
    gender: Gender;
    category: Category;
    career: Array<CareerAchievement>;
} {
    return {
        dob: value.dob,
        documents: value.documents,
        academics: from_candid_vec_n19(_uploadFile, _downloadFile, value.academics),
        name: value.name,
        email: value.email,
        gender: from_candid_Gender_n23(_uploadFile, _downloadFile, value.gender),
        category: from_candid_Category_n25(_uploadFile, _downloadFile, value.category),
        career: value.career
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marksheetRef: [] | [string];
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}): {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
} {
    return {
        marksheetRef: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.marksheetRef)),
        institution: value.institution,
        year: value.year,
        degree: value.degree,
        percentage: value.percentage
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    description: string;
    deadline: string;
    eligibility: {
        category: _Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
}): {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    description: string;
    deadline: string;
    eligibility: {
        category: Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
} {
    return {
        id: value.id,
        title: value.title,
        provider: value.provider,
        requiredDocuments: value.requiredDocuments,
        description: value.description,
        deadline: value.deadline,
        eligibility: from_candid_record_n34(_uploadFile, _downloadFile, value.eligibility)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _Category;
    requiredSkills: Array<string>;
    minPercentage: number;
    incomeLimit: bigint;
}): {
    category: Category;
    requiredSkills: Array<string>;
    minPercentage: number;
    incomeLimit: bigint;
} {
    return {
        category: from_candid_Category_n25(_uploadFile, _downloadFile, value.category),
        requiredSkills: value.requiredSkills,
        minPercentage: value.minPercentage,
        incomeLimit: value.incomeLimit
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApplicationStatus;
    userId: Principal;
    filledFields: _MasterUserRecord;
    scholarshipId: bigint;
}): {
    status: ApplicationStatus;
    userId: Principal;
    filledFields: MasterUserRecord;
    scholarshipId: bigint;
} {
    return {
        status: from_candid_ApplicationStatus_n38(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        filledFields: from_candid_MasterUserRecord_n17(_uploadFile, _downloadFile, value.filledFields),
        scholarshipId: value.scholarshipId
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    general: null;
}): Category {
    return "sc" in value ? Category.sc : "st" in value ? Category.st : "obc" in value ? Category.obc : "general" in value ? Category.general : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    underReview: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
}): ApplicationStatus {
    return "submitted" in value ? ApplicationStatus.submitted : "underReview" in value ? ApplicationStatus.underReview : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : "draft" in value ? ApplicationStatus.draft : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AcademicRecord>): Array<AcademicRecord> {
    return value.map((x)=>from_candid_AcademicRecord_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScholarshipApplication>): Array<ScholarshipApplication> {
    return value.map((x)=>from_candid_ScholarshipApplication_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Scholarship>): Array<Scholarship> {
    return value.map((x)=>from_candid_Scholarship_n32(_uploadFile, _downloadFile, x));
}
function to_candid_AcademicRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicRecord): _AcademicRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MasterUserRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MasterUserRecord): _MasterUserRecord {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ScholarshipApplication_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScholarshipApplication): _ScholarshipApplication {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Scholarship_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Scholarship): _Scholarship {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ApplicationStatus;
    userId: Principal;
    filledFields: MasterUserRecord;
    scholarshipId: bigint;
}): {
    status: _ApplicationStatus;
    userId: Principal;
    filledFields: _MasterUserRecord;
    scholarshipId: bigint;
} {
    return {
        status: to_candid_ApplicationStatus_n3(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        filledFields: to_candid_MasterUserRecord_n5(_uploadFile, _downloadFile, value.filledFields),
        scholarshipId: value.scholarshipId
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    description: string;
    deadline: string;
    eligibility: {
        category: Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
}): {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    description: string;
    deadline: string;
    eligibility: {
        category: _Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
} {
    return {
        id: value.id,
        title: value.title,
        provider: value.provider,
        requiredDocuments: value.requiredDocuments,
        description: value.description,
        deadline: value.deadline,
        eligibility: to_candid_record_n29(_uploadFile, _downloadFile, value.eligibility)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: Category;
    requiredSkills: Array<string>;
    minPercentage: number;
    incomeLimit: bigint;
}): {
    category: _Category;
    requiredSkills: Array<string>;
    minPercentage: number;
    incomeLimit: bigint;
} {
    return {
        category: to_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        requiredSkills: value.requiredSkills,
        minPercentage: value.minPercentage,
        incomeLimit: value.incomeLimit
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dob: string;
    documents: Array<DocumentReference>;
    academics: Array<AcademicRecord>;
    name: string;
    email: string;
    gender: Gender;
    category: Category;
    career: Array<CareerAchievement>;
}): {
    dob: string;
    documents: Array<_DocumentReference>;
    academics: Array<_AcademicRecord>;
    name: string;
    email: string;
    gender: _Gender;
    category: _Category;
    career: Array<_CareerAchievement>;
} {
    return {
        dob: value.dob,
        documents: value.documents,
        academics: to_candid_vec_n7(_uploadFile, _downloadFile, value.academics),
        name: value.name,
        email: value.email,
        gender: to_candid_Gender_n10(_uploadFile, _downloadFile, value.gender),
        category: to_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        career: value.career
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}): {
    marksheetRef: [] | [string];
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
} {
    return {
        marksheetRef: value.marksheetRef ? candid_some(value.marksheetRef) : candid_none(),
        institution: value.institution,
        year: value.year,
        degree: value.degree,
        percentage: value.percentage
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    general: null;
} {
    return value == Category.sc ? {
        sc: null
    } : value == Category.st ? {
        st: null
    } : value == Category.obc ? {
        obc: null
    } : value == Category.general ? {
        general: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    submitted: null;
} | {
    underReview: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
} {
    return value == ApplicationStatus.submitted ? {
        submitted: null
    } : value == ApplicationStatus.underReview ? {
        underReview: null
    } : value == ApplicationStatus.approved ? {
        approved: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AcademicRecord>): Array<_AcademicRecord> {
    return value.map((x)=>to_candid_AcademicRecord_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
