/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface DocumentRecord {
    documentName: string;
    documentType: DocumentType;
    studentId: bigint;
    uploadStatus: boolean;
    owner: Principal;
    documentId: bigint;
    remarks: string;
    verificationStatus: string;
    uploadedAt: bigint;
    fileUrl: string;
}
export interface ScholarshipApplication {
    studentId: bigint;
    applicationId: bigint;
    owner: Principal;
    rejectionReason: string;
    lastUpdated: bigint;
    applicationStatus: string;
    appliedDate: bigint;
    scholarshipId: bigint;
}
export interface CareerAchievement {
    duration: string;
    role: string;
    employer: string;
    skills: Array<string>;
}
export interface AcademicRecord {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}
export interface DocumentReference {
    documentType: string;
    uploadStatus: boolean;
    fileName: string;
}
export interface Scholarship {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    eligibleCategories: Array<string>;
    description: string;
    deadline: bigint;
    isActive: boolean;
    eligibility: {
        category: Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
    incomeLimit: bigint;
    eligibleCourseLevels: Array<string>;
}
export interface EligibilityCheckResult {
    missingDocuments: Array<string>;
    eligibilityStatus: string;
    readinessScore: bigint;
    unmetRequirements: Array<string>;
    riskLevel: string;
    urgentAlert: boolean;
}
export interface Student {
    profileCompletionPercentage: bigint;
    instituteName: string;
    documents: Array<DocumentReference>;
    studentId: bigint;
    courseLevel: string;
    academicRecords: Array<AcademicRecord>;
    owner: Principal;
    disabilityStatus: DisabilityStatus;
    createdAt: bigint;
    fullName: string;
    mobileNumber: string;
    careerAchievements: Array<CareerAchievement>;
    email: string;
    district: string;
    updatedAt: bigint;
    state: string;
    currentYear: bigint;
    gender: Gender;
    category: Category;
    courseName: string;
    annualFamilyIncome: string;
}
export enum Category {
    sc = "sc",
    st = "st",
    obc = "obc",
    general = "general"
}
export enum DisabilityStatus {
    none = "none",
    hearingImpaired = "hearingImpaired",
    physicalImpaired = "physicalImpaired",
    sightImpaired = "sightImpaired"
}
export enum DocumentType {
    Mandatory = "Mandatory",
    Conditional = "Conditional",
    Optional = "Optional"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createApplication(studentId: bigint, scholarshipId: bigint): Promise<bigint>;
    createScholarship(title: string, provider: string, deadline: bigint, description: string, requiredDocuments: Array<string>, incomeLimit: bigint, eligibleCategories: Array<string>, eligibleCourseLevels: Array<string>, isActive: boolean): Promise<bigint>;
    getApplicationsByStudent(studentId: bigint): Promise<Array<ScholarshipApplication>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocumentsByStudent(studentId: bigint): Promise<Array<DocumentRecord>>;
    getEligibilityInsights(studentId: bigint, scholarshipId: bigint): Promise<EligibilityCheckResult>;
    getMyApplications(): Promise<Array<ScholarshipApplication>>;
    getMyStudent(): Promise<Student | null>;
    getScholarshipById(scholarshipId: bigint): Promise<Scholarship | null>;
    getScholarships(): Promise<Array<Scholarship>>;
    getStudent(studentId: bigint): Promise<Student | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerStudent(fullName: string, email: string, mobile: string, course: string, category: string, income: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateApplicationStatus(applicationId: bigint, applicationStatus: string, rejectionReason: string): Promise<void>;
    updateDocumentUploadStatus(documentId: bigint, uploadStatus: boolean, fileUrl: string): Promise<void>;
    updateDocumentVerificationStatus(documentId: bigint, verificationStatus: string, remarks: string): Promise<void>;
    uploadDocument(studentId: bigint, documentName: string, filePath: string): Promise<string>;
}
import type { AcademicRecord as _AcademicRecord, CareerAchievement as _CareerAchievement, Category as _Category, DisabilityStatus as _DisabilityStatus, DocumentRecord as _DocumentRecord, DocumentReference as _DocumentReference, DocumentType as _DocumentType, Gender as _Gender, Scholarship as _Scholarship, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createApplication(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createApplication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApplication(arg0, arg1);
            return result;
        }
    }
    async createScholarship(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>, arg5: bigint, arg6: Array<string>, arg7: Array<string>, arg8: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createScholarship(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScholarship(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async getApplicationsByStudent(arg0: bigint): Promise<Array<ScholarshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsByStudent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsByStudent(arg0: bigint): Promise<Array<DocumentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByStudent(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByStudent(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEligibilityInsights(arg0: bigint, arg1: bigint): Promise<EligibilityCheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getEligibilityInsights(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEligibilityInsights(arg0, arg1);
            return result;
        }
    }
    async getMyApplications(): Promise<Array<ScholarshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return result;
        }
    }
    async getMyStudent(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStudent();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStudent();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScholarshipById(arg0: bigint): Promise<Scholarship | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScholarshipById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScholarshipById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScholarships(): Promise<Array<Scholarship>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScholarships();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScholarships();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDocumentUploadStatus(arg0: bigint, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocumentUploadStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocumentUploadStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateDocumentVerificationStatus(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocumentVerificationStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocumentVerificationStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadDocument(arg0: bigint, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AcademicRecord_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicRecord): AcademicRecord {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DisabilityStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisabilityStatus): DisabilityStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentRecord_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentRecord): DocumentRecord {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Scholarship_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scholarship): Scholarship {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Scholarship]): Scholarship | null {
    return value.length === 0 ? null : from_candid_Scholarship_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileCompletionPercentage: bigint;
    instituteName: string;
    documents: Array<_DocumentReference>;
    studentId: bigint;
    courseLevel: string;
    academicRecords: Array<_AcademicRecord>;
    owner: Principal;
    disabilityStatus: _DisabilityStatus;
    createdAt: bigint;
    fullName: string;
    mobileNumber: string;
    careerAchievements: Array<_CareerAchievement>;
    email: string;
    district: string;
    updatedAt: bigint;
    state: string;
    currentYear: bigint;
    gender: _Gender;
    category: _Category;
    courseName: string;
    annualFamilyIncome: string;
}): {
    profileCompletionPercentage: bigint;
    instituteName: string;
    documents: Array<DocumentReference>;
    studentId: bigint;
    courseLevel: string;
    academicRecords: Array<AcademicRecord>;
    owner: Principal;
    disabilityStatus: DisabilityStatus;
    createdAt: bigint;
    fullName: string;
    mobileNumber: string;
    careerAchievements: Array<CareerAchievement>;
    email: string;
    district: string;
    updatedAt: bigint;
    state: string;
    currentYear: bigint;
    gender: Gender;
    category: Category;
    courseName: string;
    annualFamilyIncome: string;
} {
    return {
        profileCompletionPercentage: value.profileCompletionPercentage,
        instituteName: value.instituteName,
        documents: value.documents,
        studentId: value.studentId,
        courseLevel: value.courseLevel,
        academicRecords: from_candid_vec_n14(_uploadFile, _downloadFile, value.academicRecords),
        owner: value.owner,
        disabilityStatus: from_candid_DisabilityStatus_n18(_uploadFile, _downloadFile, value.disabilityStatus),
        createdAt: value.createdAt,
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        careerAchievements: value.careerAchievements,
        email: value.email,
        district: value.district,
        updatedAt: value.updatedAt,
        state: value.state,
        currentYear: value.currentYear,
        gender: from_candid_Gender_n20(_uploadFile, _downloadFile, value.gender),
        category: from_candid_Category_n22(_uploadFile, _downloadFile, value.category),
        courseName: value.courseName,
        annualFamilyIncome: value.annualFamilyIncome
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marksheetRef: [] | [string];
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}): {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
} {
    return {
        marksheetRef: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.marksheetRef)),
        institution: value.institution,
        year: value.year,
        degree: value.degree,
        percentage: value.percentage
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    eligibleCategories: Array<string>;
    description: string;
    deadline: bigint;
    isActive: boolean;
    eligibility: {
        category: _Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
    incomeLimit: bigint;
    eligibleCourseLevels: Array<string>;
}): {
    id: bigint;
    title: string;
    provider: string;
    requiredDocuments: Array<string>;
    eligibleCategories: Array<string>;
    description: string;
    deadline: bigint;
    isActive: boolean;
    eligibility: {
        category: Category;
        requiredSkills: Array<string>;
        minPercentage: number;
        incomeLimit: bigint;
    };
    incomeLimit: bigint;
    eligibleCourseLevels: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        provider: value.provider,
        requiredDocuments: value.requiredDocuments,
        eligibleCategories: value.eligibleCategories,
        description: value.description,
        deadline: value.deadline,
        isActive: value.isActive,
        eligibility: from_candid_record_n27(_uploadFile, _downloadFile, value.eligibility),
        incomeLimit: value.incomeLimit,
        eligibleCourseLevels: value.eligibleCourseLevels
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _Category;
    requiredSkills: Array<string>;
    minPercentage: number;
    incomeLimit: bigint;
}): {
    category: Category;
    requiredSkills: Array<string>;
    minPercentage: number;
    incomeLimit: bigint;
} {
    return {
        category: from_candid_Category_n22(_uploadFile, _downloadFile, value.category),
        requiredSkills: value.requiredSkills,
        minPercentage: value.minPercentage,
        incomeLimit: value.incomeLimit
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documentName: string;
    documentType: _DocumentType;
    studentId: bigint;
    uploadStatus: boolean;
    owner: Principal;
    documentId: bigint;
    remarks: string;
    verificationStatus: string;
    uploadedAt: bigint;
    fileUrl: string;
}): {
    documentName: string;
    documentType: DocumentType;
    studentId: bigint;
    uploadStatus: boolean;
    owner: Principal;
    documentId: bigint;
    remarks: string;
    verificationStatus: string;
    uploadedAt: bigint;
    fileUrl: string;
} {
    return {
        documentName: value.documentName,
        documentType: from_candid_DocumentType_n9(_uploadFile, _downloadFile, value.documentType),
        studentId: value.studentId,
        uploadStatus: value.uploadStatus,
        owner: value.owner,
        documentId: value.documentId,
        remarks: value.remarks,
        verificationStatus: value.verificationStatus,
        uploadedAt: value.uploadedAt,
        fileUrl: value.fileUrl
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mandatory: null;
} | {
    Conditional: null;
} | {
    Optional: null;
}): DocumentType {
    return "Mandatory" in value ? DocumentType.Mandatory : "Conditional" in value ? DocumentType.Conditional : "Optional" in value ? DocumentType.Optional : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    hearingImpaired: null;
} | {
    physicalImpaired: null;
} | {
    sightImpaired: null;
}): DisabilityStatus {
    return "none" in value ? DisabilityStatus.none : "hearingImpaired" in value ? DisabilityStatus.hearingImpaired : "physicalImpaired" in value ? DisabilityStatus.physicalImpaired : "sightImpaired" in value ? DisabilityStatus.sightImpaired : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    general: null;
}): Category {
    return "sc" in value ? Category.sc : "st" in value ? Category.st : "obc" in value ? Category.obc : "general" in value ? Category.general : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AcademicRecord>): Array<AcademicRecord> {
    return value.map((x)=>from_candid_AcademicRecord_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Scholarship>): Array<Scholarship> {
    return value.map((x)=>from_candid_Scholarship_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentRecord>): Array<DocumentRecord> {
    return value.map((x)=>from_candid_DocumentRecord_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
