/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScholarshipApplication = IDL.Record({
  'studentId' : IDL.Nat,
  'applicationId' : IDL.Nat,
  'owner' : IDL.Principal,
  'rejectionReason' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'applicationStatus' : IDL.Text,
  'appliedDate' : IDL.Int,
  'scholarshipId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const DocumentType = IDL.Variant({
  'Mandatory' : IDL.Null,
  'Conditional' : IDL.Null,
  'Optional' : IDL.Null,
});
export const DocumentRecord = IDL.Record({
  'documentName' : IDL.Text,
  'documentType' : DocumentType,
  'studentId' : IDL.Nat,
  'uploadStatus' : IDL.Bool,
  'owner' : IDL.Principal,
  'documentId' : IDL.Nat,
  'remarks' : IDL.Text,
  'verificationStatus' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'fileUrl' : IDL.Text,
});
export const EligibilityCheckResult = IDL.Record({
  'missingDocuments' : IDL.Vec(IDL.Text),
  'eligibilityStatus' : IDL.Text,
  'readinessScore' : IDL.Nat,
  'unmetRequirements' : IDL.Vec(IDL.Text),
  'riskLevel' : IDL.Text,
  'urgentAlert' : IDL.Bool,
});
export const DocumentReference = IDL.Record({
  'documentType' : IDL.Text,
  'uploadStatus' : IDL.Bool,
  'fileName' : IDL.Text,
});
export const AcademicRecord = IDL.Record({
  'marksheetRef' : IDL.Opt(IDL.Text),
  'institution' : IDL.Text,
  'year' : IDL.Nat,
  'degree' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const DisabilityStatus = IDL.Variant({
  'none' : IDL.Null,
  'hearingImpaired' : IDL.Null,
  'physicalImpaired' : IDL.Null,
  'sightImpaired' : IDL.Null,
});
export const CareerAchievement = IDL.Record({
  'duration' : IDL.Text,
  'role' : IDL.Text,
  'employer' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Category = IDL.Variant({
  'sc' : IDL.Null,
  'st' : IDL.Null,
  'obc' : IDL.Null,
  'general' : IDL.Null,
});
export const Student = IDL.Record({
  'profileCompletionPercentage' : IDL.Nat,
  'instituteName' : IDL.Text,
  'documents' : IDL.Vec(DocumentReference),
  'studentId' : IDL.Nat,
  'courseLevel' : IDL.Text,
  'academicRecords' : IDL.Vec(AcademicRecord),
  'owner' : IDL.Principal,
  'disabilityStatus' : DisabilityStatus,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'careerAchievements' : IDL.Vec(CareerAchievement),
  'email' : IDL.Text,
  'district' : IDL.Text,
  'updatedAt' : IDL.Int,
  'state' : IDL.Text,
  'currentYear' : IDL.Nat,
  'gender' : Gender,
  'category' : Category,
  'courseName' : IDL.Text,
  'annualFamilyIncome' : IDL.Text,
});
export const Scholarship = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'provider' : IDL.Text,
  'requiredDocuments' : IDL.Vec(IDL.Text),
  'eligibleCategories' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'deadline' : IDL.Int,
  'isActive' : IDL.Bool,
  'eligibility' : IDL.Record({
    'category' : Category,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'minPercentage' : IDL.Float64,
    'incomeLimit' : IDL.Nat,
  }),
  'incomeLimit' : IDL.Nat,
  'eligibleCourseLevels' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createApplication' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createScholarship' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'getApplicationsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ScholarshipApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DocumentRecord)],
      ['query'],
    ),
  'getEligibilityInsights' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [EligibilityCheckResult],
      ['query'],
    ),
  'getMyApplications' : IDL.Func(
      [],
      [IDL.Vec(ScholarshipApplication)],
      ['query'],
    ),
  'getMyStudent' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getScholarshipById' : IDL.Func([IDL.Nat], [IDL.Opt(Scholarship)], ['query']),
  'getScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateDocumentUploadStatus' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'updateDocumentVerificationStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScholarshipApplication = IDL.Record({
    'studentId' : IDL.Nat,
    'applicationId' : IDL.Nat,
    'owner' : IDL.Principal,
    'rejectionReason' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'applicationStatus' : IDL.Text,
    'appliedDate' : IDL.Int,
    'scholarshipId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const DocumentType = IDL.Variant({
    'Mandatory' : IDL.Null,
    'Conditional' : IDL.Null,
    'Optional' : IDL.Null,
  });
  const DocumentRecord = IDL.Record({
    'documentName' : IDL.Text,
    'documentType' : DocumentType,
    'studentId' : IDL.Nat,
    'uploadStatus' : IDL.Bool,
    'owner' : IDL.Principal,
    'documentId' : IDL.Nat,
    'remarks' : IDL.Text,
    'verificationStatus' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'fileUrl' : IDL.Text,
  });
  const EligibilityCheckResult = IDL.Record({
    'missingDocuments' : IDL.Vec(IDL.Text),
    'eligibilityStatus' : IDL.Text,
    'readinessScore' : IDL.Nat,
    'unmetRequirements' : IDL.Vec(IDL.Text),
    'riskLevel' : IDL.Text,
    'urgentAlert' : IDL.Bool,
  });
  const DocumentReference = IDL.Record({
    'documentType' : IDL.Text,
    'uploadStatus' : IDL.Bool,
    'fileName' : IDL.Text,
  });
  const AcademicRecord = IDL.Record({
    'marksheetRef' : IDL.Opt(IDL.Text),
    'institution' : IDL.Text,
    'year' : IDL.Nat,
    'degree' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const DisabilityStatus = IDL.Variant({
    'none' : IDL.Null,
    'hearingImpaired' : IDL.Null,
    'physicalImpaired' : IDL.Null,
    'sightImpaired' : IDL.Null,
  });
  const CareerAchievement = IDL.Record({
    'duration' : IDL.Text,
    'role' : IDL.Text,
    'employer' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Category = IDL.Variant({
    'sc' : IDL.Null,
    'st' : IDL.Null,
    'obc' : IDL.Null,
    'general' : IDL.Null,
  });
  const Student = IDL.Record({
    'profileCompletionPercentage' : IDL.Nat,
    'instituteName' : IDL.Text,
    'documents' : IDL.Vec(DocumentReference),
    'studentId' : IDL.Nat,
    'courseLevel' : IDL.Text,
    'academicRecords' : IDL.Vec(AcademicRecord),
    'owner' : IDL.Principal,
    'disabilityStatus' : DisabilityStatus,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'careerAchievements' : IDL.Vec(CareerAchievement),
    'email' : IDL.Text,
    'district' : IDL.Text,
    'updatedAt' : IDL.Int,
    'state' : IDL.Text,
    'currentYear' : IDL.Nat,
    'gender' : Gender,
    'category' : Category,
    'courseName' : IDL.Text,
    'annualFamilyIncome' : IDL.Text,
  });
  const Scholarship = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'provider' : IDL.Text,
    'requiredDocuments' : IDL.Vec(IDL.Text),
    'eligibleCategories' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'deadline' : IDL.Int,
    'isActive' : IDL.Bool,
    'eligibility' : IDL.Record({
      'category' : Category,
      'requiredSkills' : IDL.Vec(IDL.Text),
      'minPercentage' : IDL.Float64,
      'incomeLimit' : IDL.Nat,
    }),
    'incomeLimit' : IDL.Nat,
    'eligibleCourseLevels' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createApplication' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createScholarship' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'getApplicationsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ScholarshipApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DocumentRecord)],
        ['query'],
      ),
    'getEligibilityInsights' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [EligibilityCheckResult],
        ['query'],
      ),
    'getMyApplications' : IDL.Func(
        [],
        [IDL.Vec(ScholarshipApplication)],
        ['query'],
      ),
    'getMyStudent' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getScholarshipById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Scholarship)],
        ['query'],
      ),
    'getScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateDocumentUploadStatus' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'updateDocumentVerificationStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };