/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicRecord {
  'marksheetRef' : [] | [string],
  'institution' : string,
  'year' : bigint,
  'degree' : string,
  'percentage' : number,
}
export type ApplicationStatus = { 'submitted' : null } |
  { 'underReview' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface CareerAchievement {
  'duration' : string,
  'role' : string,
  'employer' : string,
  'skills' : Array<string>,
}
export type Category = { 'sc' : null } |
  { 'st' : null } |
  { 'obc' : null } |
  { 'general' : null };
export interface DocumentReference {
  'documentType' : string,
  'uploadStatus' : boolean,
  'fileName' : string,
}
export interface EligibilityCheckResult {
  'missingDocuments' : Array<string>,
  'isEligible' : boolean,
  'unmetRequirements' : Array<string>,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface MasterUserRecord {
  'dob' : string,
  'documents' : Array<DocumentReference>,
  'academics' : Array<AcademicRecord>,
  'name' : string,
  'email' : string,
  'gender' : Gender,
  'category' : Category,
  'career' : Array<CareerAchievement>,
}
export interface ProfileCompletionResult {
  'completionPercentage' : number,
  'missingFields' : Array<string>,
}
export interface Scholarship {
  'id' : bigint,
  'title' : string,
  'provider' : string,
  'requiredDocuments' : Array<string>,
  'description' : string,
  'deadline' : string,
  'eligibility' : {
    'category' : Category,
    'requiredSkills' : Array<string>,
    'minPercentage' : number,
    'incomeLimit' : bigint,
  },
}
export interface ScholarshipApplication {
  'status' : ApplicationStatus,
  'userId' : Principal,
  'filledFields' : MasterUserRecord,
  'scholarshipId' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Apply to a scholarship. Requires #user role.
   */
  'applyToScholarship' : ActorMethod<
    [bigint, ScholarshipApplication],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Return a pre-populated application form from the user's Master User Record.
   * / Caller must be the owner of the record or an admin, because this exposes
   * / private personal, academic, and career data.
   */
  'autoFillApplication' : ActorMethod<
    [bigint, Principal],
    [] | [MasterUserRecord]
  >,
  /**
   * / Check eligibility of a user for a scholarship.
   * / Caller must be the owner of the record or an admin, because the result
   * / exposes private academic and career data.
   */
  'checkEligibility' : ActorMethod<[bigint, Principal], EligibilityCheckResult>,
  /**
   * / Create a new scholarship. Admin only.
   */
  'createScholarship' : ActorMethod<[Scholarship], bigint>,
  /**
   * / Get the calling user's own Master User Record.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [MasterUserRecord]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Calculate the profile completion score for a user.
   * / Caller must be the owner of the record or an admin, because the result
   * / reveals which private fields are missing.
   */
  'getProfileCompletion' : ActorMethod<[Principal], ProfileCompletionResult>,
  /**
   * / Get a single scholarship by id. Public — no auth required.
   */
  'getScholarship' : ActorMethod<[bigint], Scholarship>,
  /**
   * / Retrieve all applications for a user. Caller must be the owner or an admin.
   */
  'getUserApplications' : ActorMethod<
    [Principal],
    Array<ScholarshipApplication>
  >,
  /**
   * / Fetch another user's profile. Caller must be the owner or an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [MasterUserRecord]>,
  /**
   * / Retrieve a user record. Caller must be the owner or an admin.
   */
  'getUserRecord' : ActorMethod<[Principal], [] | [MasterUserRecord]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all scholarships. Public — no auth required.
   */
  'listScholarships' : ActorMethod<[], Array<Scholarship>>,
  /**
   * / Save/update the calling user's own Master User Record.
   */
  'saveCallerUserProfile' : ActorMethod<[MasterUserRecord], undefined>,
  /**
   * / Update the calling user's own Master User Record.
   */
  'updateUserRecord' : ActorMethod<[MasterUserRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];