/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const DocumentReference = IDL.Record({
  'documentType' : IDL.Text,
  'uploadStatus' : IDL.Bool,
  'fileName' : IDL.Text,
});
export const AcademicRecord = IDL.Record({
  'marksheetRef' : IDL.Opt(IDL.Text),
  'institution' : IDL.Text,
  'year' : IDL.Nat,
  'degree' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Category = IDL.Variant({
  'sc' : IDL.Null,
  'st' : IDL.Null,
  'obc' : IDL.Null,
  'general' : IDL.Null,
});
export const CareerAchievement = IDL.Record({
  'duration' : IDL.Text,
  'role' : IDL.Text,
  'employer' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const MasterUserRecord = IDL.Record({
  'dob' : IDL.Text,
  'documents' : IDL.Vec(DocumentReference),
  'academics' : IDL.Vec(AcademicRecord),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'category' : Category,
  'career' : IDL.Vec(CareerAchievement),
});
export const ScholarshipApplication = IDL.Record({
  'status' : ApplicationStatus,
  'userId' : IDL.Principal,
  'filledFields' : MasterUserRecord,
  'scholarshipId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EligibilityCheckResult = IDL.Record({
  'missingDocuments' : IDL.Vec(IDL.Text),
  'isEligible' : IDL.Bool,
  'unmetRequirements' : IDL.Vec(IDL.Text),
});
export const Scholarship = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'provider' : IDL.Text,
  'requiredDocuments' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'eligibility' : IDL.Record({
    'category' : Category,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'minPercentage' : IDL.Float64,
    'incomeLimit' : IDL.Nat,
  }),
});
export const ProfileCompletionResult = IDL.Record({
  'completionPercentage' : IDL.Float64,
  'missingFields' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToScholarship' : IDL.Func([IDL.Nat, ScholarshipApplication], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'autoFillApplication' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [IDL.Opt(MasterUserRecord)],
      ['query'],
    ),
  'checkEligibility' : IDL.Func(
      [IDL.Nat, IDL.Principal],
      [EligibilityCheckResult],
      ['query'],
    ),
  'createScholarship' : IDL.Func([Scholarship], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(MasterUserRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfileCompletion' : IDL.Func(
      [IDL.Principal],
      [ProfileCompletionResult],
      ['query'],
    ),
  'getScholarship' : IDL.Func([IDL.Nat], [Scholarship], ['query']),
  'getUserApplications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScholarshipApplication)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MasterUserRecord)],
      ['query'],
    ),
  'getUserRecord' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MasterUserRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
  'saveCallerUserProfile' : IDL.Func([MasterUserRecord], [], []),
  'updateUserRecord' : IDL.Func([MasterUserRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const DocumentReference = IDL.Record({
    'documentType' : IDL.Text,
    'uploadStatus' : IDL.Bool,
    'fileName' : IDL.Text,
  });
  const AcademicRecord = IDL.Record({
    'marksheetRef' : IDL.Opt(IDL.Text),
    'institution' : IDL.Text,
    'year' : IDL.Nat,
    'degree' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Category = IDL.Variant({
    'sc' : IDL.Null,
    'st' : IDL.Null,
    'obc' : IDL.Null,
    'general' : IDL.Null,
  });
  const CareerAchievement = IDL.Record({
    'duration' : IDL.Text,
    'role' : IDL.Text,
    'employer' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const MasterUserRecord = IDL.Record({
    'dob' : IDL.Text,
    'documents' : IDL.Vec(DocumentReference),
    'academics' : IDL.Vec(AcademicRecord),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'category' : Category,
    'career' : IDL.Vec(CareerAchievement),
  });
  const ScholarshipApplication = IDL.Record({
    'status' : ApplicationStatus,
    'userId' : IDL.Principal,
    'filledFields' : MasterUserRecord,
    'scholarshipId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EligibilityCheckResult = IDL.Record({
    'missingDocuments' : IDL.Vec(IDL.Text),
    'isEligible' : IDL.Bool,
    'unmetRequirements' : IDL.Vec(IDL.Text),
  });
  const Scholarship = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'provider' : IDL.Text,
    'requiredDocuments' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'eligibility' : IDL.Record({
      'category' : Category,
      'requiredSkills' : IDL.Vec(IDL.Text),
      'minPercentage' : IDL.Float64,
      'incomeLimit' : IDL.Nat,
    }),
  });
  const ProfileCompletionResult = IDL.Record({
    'completionPercentage' : IDL.Float64,
    'missingFields' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToScholarship' : IDL.Func([IDL.Nat, ScholarshipApplication], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'autoFillApplication' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Opt(MasterUserRecord)],
        ['query'],
      ),
    'checkEligibility' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [EligibilityCheckResult],
        ['query'],
      ),
    'createScholarship' : IDL.Func([Scholarship], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(MasterUserRecord)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfileCompletion' : IDL.Func(
        [IDL.Principal],
        [ProfileCompletionResult],
        ['query'],
      ),
    'getScholarship' : IDL.Func([IDL.Nat], [Scholarship], ['query']),
    'getUserApplications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScholarshipApplication)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MasterUserRecord)],
        ['query'],
      ),
    'getUserRecord' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MasterUserRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
    'saveCallerUserProfile' : IDL.Func([MasterUserRecord], [], []),
    'updateUserRecord' : IDL.Func([MasterUserRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };