/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicRecord {
  'marksheetRef' : [] | [string],
  'institution' : string,
  'year' : bigint,
  'degree' : string,
  'percentage' : number,
}
export interface CareerAchievement {
  'duration' : string,
  'role' : string,
  'employer' : string,
  'skills' : Array<string>,
}
export type Category = { 'sc' : null } |
  { 'st' : null } |
  { 'obc' : null } |
  { 'general' : null };
export type DisabilityStatus = { 'none' : null } |
  { 'hearingImpaired' : null } |
  { 'physicalImpaired' : null } |
  { 'sightImpaired' : null };
export interface DocumentRecord {
  'documentName' : string,
  'documentType' : DocumentType,
  'studentId' : bigint,
  'uploadStatus' : boolean,
  'owner' : Principal,
  'documentId' : bigint,
  'remarks' : string,
  'verificationStatus' : string,
  'uploadedAt' : bigint,
  'fileUrl' : string,
}
export interface DocumentReference {
  'documentType' : string,
  'uploadStatus' : boolean,
  'fileName' : string,
}
export type DocumentType = { 'Mandatory' : null } |
  { 'Conditional' : null } |
  { 'Optional' : null };
export interface EligibilityCheckResult {
  'missingDocuments' : Array<string>,
  'eligibilityStatus' : string,
  'readinessScore' : bigint,
  'unmetRequirements' : Array<string>,
  'riskLevel' : string,
  'urgentAlert' : boolean,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Scholarship {
  'id' : bigint,
  'title' : string,
  'provider' : string,
  'requiredDocuments' : Array<string>,
  'eligibleCategories' : Array<string>,
  'description' : string,
  'deadline' : bigint,
  'isActive' : boolean,
  'eligibility' : {
    'category' : Category,
    'requiredSkills' : Array<string>,
    'minPercentage' : number,
    'incomeLimit' : bigint,
  },
  'incomeLimit' : bigint,
  'eligibleCourseLevels' : Array<string>,
}
export interface ScholarshipApplication {
  'studentId' : bigint,
  'applicationId' : bigint,
  'owner' : Principal,
  'rejectionReason' : string,
  'lastUpdated' : bigint,
  'applicationStatus' : string,
  'appliedDate' : bigint,
  'scholarshipId' : bigint,
}
export interface Student {
  'profileCompletionPercentage' : bigint,
  'instituteName' : string,
  'documents' : Array<DocumentReference>,
  'studentId' : bigint,
  'courseLevel' : string,
  'academicRecords' : Array<AcademicRecord>,
  'owner' : Principal,
  'disabilityStatus' : DisabilityStatus,
  'createdAt' : bigint,
  'fullName' : string,
  'mobileNumber' : string,
  'careerAchievements' : Array<CareerAchievement>,
  'email' : string,
  'district' : string,
  'updatedAt' : bigint,
  'state' : string,
  'currentYear' : bigint,
  'gender' : Gender,
  'category' : Category,
  'courseName' : string,
  'annualFamilyIncome' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createApplication' : ActorMethod<[bigint, bigint], bigint>,
  'createScholarship' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      Array<string>,
      bigint,
      Array<string>,
      Array<string>,
      boolean,
    ],
    bigint
  >,
  'getApplicationsByStudent' : ActorMethod<
    [bigint],
    Array<ScholarshipApplication>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocumentsByStudent' : ActorMethod<[bigint], Array<DocumentRecord>>,
  'getEligibilityInsights' : ActorMethod<
    [bigint, bigint],
    EligibilityCheckResult
  >,
  'getMyApplications' : ActorMethod<[], Array<ScholarshipApplication>>,
  'getMyStudent' : ActorMethod<[], [] | [Student]>,
  'getScholarshipById' : ActorMethod<[bigint], [] | [Scholarship]>,
  'getScholarships' : ActorMethod<[], Array<Scholarship>>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStudent' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<[bigint, string, string], undefined>,
  'updateDocumentUploadStatus' : ActorMethod<
    [bigint, boolean, string],
    undefined
  >,
  'updateDocumentVerificationStatus' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'uploadDocument' : ActorMethod<[bigint, string, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];