/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    profileCompletionPercentage: bigint;
    instituteName: string;
    documents: Array<DocumentReference>;
    courseLevel: string;
    academicRecords: Array<AcademicRecord>;
    owner: Principal;
    disabilityStatus: DisabilityStatus;
    createdAt: bigint;
    profileId: bigint;
    fullName: string;
    mobileNumber: string;
    careerAchievements: Array<CareerAchievement>;
    email: string;
    district: string;
    updatedAt: bigint;
    state: string;
    currentYear: bigint;
    gender: Gender;
    category: Category;
    courseName: string;
    annualFamilyIncome: string;
}
export interface DocumentReference {
    documentType: string;
    uploadStatus: boolean;
    fileName: string;
}
export interface DocumentVerificationResult {
    status: Variant_V2_Approved_Rejected_Pending;
    updatedTimestamp: bigint;
    reason: string;
}
export interface CareerAchievement {
    duration: string;
    role: string;
    employer: string;
    skills: Array<string>;
}
export interface AcademicRecord {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum Category {
    sc = "sc",
    st = "st",
    obc = "obc",
    general = "general"
}
export enum DisabilityStatus {
    none = "none",
    hearingImpaired = "hearingImpaired",
    physicalImpaired = "physicalImpaired",
    sightImpaired = "sightImpaired"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_V2_Approved_Rejected_Pending {
    V2 = "V2",
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cleanDemoStudents(): Promise<string>;
    connectDigiLocker(studentId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyProfile(): Promise<Student | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Load demo students (admin-only).
     */
    loadDemoStudents(): Promise<void>;
    registerStudent(fullName: string, email: string, mobileNumber: string, gender: Gender, category: Category, disabilityStatus: DisabilityStatus, annualFamilyIncome: string, state: string, district: string, courseName: string, courseLevel: string, instituteName: string, currentYear: bigint): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    uploadDocument(studentId: bigint, documentName: string, filePath: string): Promise<string>;
    verifyDocument(studentId: bigint, documentType: string, ocrText: string): Promise<DocumentVerificationResult>;
}
import type { AcademicRecord as _AcademicRecord, CareerAchievement as _CareerAchievement, Category as _Category, DisabilityStatus as _DisabilityStatus, DocumentReference as _DocumentReference, DocumentVerificationResult as _DocumentVerificationResult, Gender as _Gender, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cleanDemoStudents(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanDemoStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanDemoStudents();
            return result;
        }
    }
    async connectDigiLocker(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectDigiLocker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectDigiLocker(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loadDemoStudents(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.loadDemoStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadDemoStudents();
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string, arg3: Gender, arg4: Category, arg5: DisabilityStatus, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: bigint): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2, to_candid_Gender_n19(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n21(this._uploadFile, this._downloadFile, arg4), to_candid_DisabilityStatus_n23(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2, to_candid_Gender_n19(this._uploadFile, this._downloadFile, arg3), to_candid_Category_n21(this._uploadFile, this._downloadFile, arg4), to_candid_DisabilityStatus_n23(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async uploadDocument(arg0: bigint, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyDocument(arg0: bigint, arg1: string, arg2: string): Promise<DocumentVerificationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDocument(arg0, arg1, arg2);
                return from_candid_DocumentVerificationResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDocument(arg0, arg1, arg2);
            return from_candid_DocumentVerificationResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AcademicRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicRecord): AcademicRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_DisabilityStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisabilityStatus): DisabilityStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentVerificationResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentVerificationResult): DocumentVerificationResult {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marksheetRef: [] | [string];
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
}): {
    marksheetRef?: string;
    institution: string;
    year: bigint;
    degree: string;
    percentage: number;
} {
    return {
        marksheetRef: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.marksheetRef)),
        institution: value.institution,
        year: value.year,
        degree: value.degree,
        percentage: value.percentage
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        V2: null;
    } | {
        Approved: null;
    } | {
        Rejected: null;
    } | {
        Pending: null;
    };
    updatedTimestamp: bigint;
    reason: string;
}): {
    status: Variant_V2_Approved_Rejected_Pending;
    updatedTimestamp: bigint;
    reason: string;
} {
    return {
        status: from_candid_variant_n28(_uploadFile, _downloadFile, value.status),
        updatedTimestamp: value.updatedTimestamp,
        reason: value.reason
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileCompletionPercentage: bigint;
    instituteName: string;
    documents: Array<_DocumentReference>;
    courseLevel: string;
    academicRecords: Array<_AcademicRecord>;
    owner: Principal;
    disabilityStatus: _DisabilityStatus;
    createdAt: bigint;
    profileId: bigint;
    fullName: string;
    mobileNumber: string;
    careerAchievements: Array<_CareerAchievement>;
    email: string;
    district: string;
    updatedAt: bigint;
    state: string;
    currentYear: bigint;
    gender: _Gender;
    category: _Category;
    courseName: string;
    annualFamilyIncome: string;
}): {
    profileCompletionPercentage: bigint;
    instituteName: string;
    documents: Array<DocumentReference>;
    courseLevel: string;
    academicRecords: Array<AcademicRecord>;
    owner: Principal;
    disabilityStatus: DisabilityStatus;
    createdAt: bigint;
    profileId: bigint;
    fullName: string;
    mobileNumber: string;
    careerAchievements: Array<CareerAchievement>;
    email: string;
    district: string;
    updatedAt: bigint;
    state: string;
    currentYear: bigint;
    gender: Gender;
    category: Category;
    courseName: string;
    annualFamilyIncome: string;
} {
    return {
        profileCompletionPercentage: value.profileCompletionPercentage,
        instituteName: value.instituteName,
        documents: value.documents,
        courseLevel: value.courseLevel,
        academicRecords: from_candid_vec_n9(_uploadFile, _downloadFile, value.academicRecords),
        owner: value.owner,
        disabilityStatus: from_candid_DisabilityStatus_n13(_uploadFile, _downloadFile, value.disabilityStatus),
        createdAt: value.createdAt,
        profileId: value.profileId,
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        careerAchievements: value.careerAchievements,
        email: value.email,
        district: value.district,
        updatedAt: value.updatedAt,
        state: value.state,
        currentYear: value.currentYear,
        gender: from_candid_Gender_n15(_uploadFile, _downloadFile, value.gender),
        category: from_candid_Category_n17(_uploadFile, _downloadFile, value.category),
        courseName: value.courseName,
        annualFamilyIncome: value.annualFamilyIncome
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    hearingImpaired: null;
} | {
    physicalImpaired: null;
} | {
    sightImpaired: null;
}): DisabilityStatus {
    return "none" in value ? DisabilityStatus.none : "hearingImpaired" in value ? DisabilityStatus.hearingImpaired : "physicalImpaired" in value ? DisabilityStatus.physicalImpaired : "sightImpaired" in value ? DisabilityStatus.sightImpaired : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    general: null;
}): Category {
    return "sc" in value ? Category.sc : "st" in value ? Category.st : "obc" in value ? Category.obc : "general" in value ? Category.general : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    V2: null;
} | {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): Variant_V2_Approved_Rejected_Pending {
    return "V2" in value ? Variant_V2_Approved_Rejected_Pending.V2 : "Approved" in value ? Variant_V2_Approved_Rejected_Pending.Approved : "Rejected" in value ? Variant_V2_Approved_Rejected_Pending.Rejected : "Pending" in value ? Variant_V2_Approved_Rejected_Pending.Pending : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AcademicRecord>): Array<AcademicRecord> {
    return value.map((x)=>from_candid_AcademicRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_DisabilityStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisabilityStatus): _DisabilityStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    general: null;
} {
    return value == Category.sc ? {
        sc: null
    } : value == Category.st ? {
        st: null
    } : value == Category.obc ? {
        obc: null
    } : value == Category.general ? {
        general: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisabilityStatus): {
    none: null;
} | {
    hearingImpaired: null;
} | {
    physicalImpaired: null;
} | {
    sightImpaired: null;
} {
    return value == DisabilityStatus.none ? {
        none: null
    } : value == DisabilityStatus.hearingImpaired ? {
        hearingImpaired: null
    } : value == DisabilityStatus.physicalImpaired ? {
        physicalImpaired: null
    } : value == DisabilityStatus.sightImpaired ? {
        sightImpaired: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
